name: Build JAR and Upload to Github Package - Product Microservice

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull from ${{ github.repository }}
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml   
    - name: Upload Package
    - uses: actions/upload-artifact@v3
      with:
        name: products:latest
        path: /home/runner/work/MS-Products/MS-Products/target/products-service-example-0.0.1-spring-boot.jar
