# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build JAR - Product Microservice

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Pull from ${{ github.repository }}
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml   
#    - name: Push to ${{ github.repository }}
#      uses: github-actions-x/commit@v2.9
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        push-branch: 'master'
#        commit-message: 'publish'
#        force-add: 'true'
#        files: target/
#        name: Hernan M Calisto
#        email: hernantvg@gmail.com
    
    - uses: actions/checkout@master
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'target/products-service-example-0.0.1-spring-boot.jar'
         


